drivers: samsung: debug: sec_debug_base_built.c: use get_kernel_nofault instead of probe_kernel_address
BPF maccess backport renamed probe_kernel_address to get_kernel_nofault to better describe the helper and match the naming of copy_from_kernel_nofault.

../drivers/samsung/debug/sec_debug_base_built.c:105:15: error: implicit declaration of function 'probe_kernel_address' [-Werror,-Wimplicit-function-declaration]
  105 |                         } else if (probe_kernel_address(p, data)) {
      |                                    ^
../drivers/samsung/debug/sec_debug_base_built.c:105:39: warning: variable 'data' is uninitialized when used here [-Wuninitialized]
  105 |                         } else if (probe_kernel_address(p, data)) {
      |                                                            ^~~~
../drivers/samsung/debug/sec_debug_base_built.c:96:12: note: initialize the variable 'data' to silence this warning  CC [M]  drivers/spi/spidev.o

   96 |                         u32     data;
      |                                     ^
      |

Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>