sound: soc/samsung: vts: Include missing compat.h header
../sound/soc/samsung/vts/vts.c:3234:41: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
 3234 |         return vts_fio_common_ioctl(file, cmd, compat_ptr(_arg));
      |                                                ^
../sound/soc/samsung/vts/vts.c:3234:41: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'int *' [-Wint-conversion]
 3234 |         return vts_fio_common_ioctl(file, cmd, compat_ptr(_arg));
      |                                                ^~~~~~~~~~~~~~~~
../sound/soc/samsung/vts/vts.c:3177:33: note: passing argument to parameter '_arg' here
 3177 |                 unsigned int cmd, int __user *_arg)
      |                                               ^
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>