bcmdhd: Remove unused variable `verboselog_ts_saved`
This gets set but never actually consumed anywhere. Clang 23 catches it
and throws an error:

../drivers/net/wireless/broadcom/bcmdhd_101_18/dhd_debug.c:432:15: error: variable 'verboselog_ts_saved' set but not used [-Werror,-Wunused-but-set-global]
  432 | static uint64 verboselog_ts_saved = 0;
      |               ^
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>