iommu: samsung-iommu: Update to use iommu_ops.map()
../drivers/iommu/samsung-iommu.c:940:11: error: incompatible function pointer types initializing 'int (*)(struct iommu_domain *, unsigned long, phys_addr_t, size_t, int, gfp_t)' (aka 'int (*)(struct iommu_domain *, unsigned long, unsigned long long, unsigned long, int, unsigned int)') with an expression of type 'int (struct iommu_domain *, unsigned long, phys_addr_t, size_t, int)' (aka 'int (struct iommu_domain *, unsigned long, unsigned long long, unsigned long, int)') [-Wincompatible-function-pointer-types]
  940 |         .map                    = samsung_sysmmu_map,
      |                                   ^~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>