fs: crypto: Fix SDP/DDAR code after API change
../fs/crypto/keysetup.c:1039:6: error: incompatible pointer types assigning to 'struct key *' from 'struct fscrypt_master_key *' [-Wincompatible-pointer-types]
 1039 |         key = fscrypt_find_master_key(ci->ci_inode->i_sb, &mk_spec);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Because commit 641403d9646a ("stop using keyrings subsystem for fscrypt_master_key")
changed the API.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>