ipv4: sysctl: Fix build error after reverts
Commit [1] added an ssthresh metrics cache knob using the old range variables,
which was fine until my mass revert.

../net/ipv4/sysctl_net_ipv4.c:1133:15: error: use of undeclared identifier 'zero'
 1133 |                 .extra1         = &zero,
      |                                    ^~~~
../net/ipv4/sysctl_net_ipv4.c:1134:15: error: use of undeclared identifier 'one'
 1134 |                 .extra2         = &one,
      |                                    ^~~
../net/ipv4/sysctl_net_ipv4.c:1282:32: error: invalid application of 'sizeof' to an incomplete type 'struct ctl_table[]'
 1282 |                 table = kmemdup(table, sizeof(ipv4_net_table), GFP_KERNEL);
      |                                              ^~~~~~~~~~~~~~~~
../net/ipv4/sysctl_net_ipv4.c:1287:19: error: invalid application of 'sizeof' to an incomplete type 'struct ctl_table[]'
 1287 |                 for (i = 0; i < ARRAY_SIZE(ipv4_net_table) - 1; i++)
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/kernel.h:47:32: note: expanded from macro 'ARRAY_SIZE'
   47 | #define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + __must_be_array(arr))
      |                                ^~~~~
4 errors generated.

[1] c16c3e91bbc9 ("net/ipv4/tcp_ipv4.c: Disable TCP ssthresh metrics cache")

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>