hid: hid-core: Fix missing code after android12-5.4 conversion
Made a mess here.

../drivers/hid/hid-core.c:292:3: error: use of undeclared identifier 'max_buffer_size'; did you mean 'max_mem_size'?
  292 |                 max_buffer_size = UHID_DATA_MAX;
      |                 ^~~~~~~~~~~~~~~
      |                 max_mem_size
../include/linux/memory_hotplug.h:116:12: note: 'max_mem_size' declared here
  116 | extern u64 max_mem_size;
      |            ^
../drivers/hid/hid-core.c:292:21: error: use of undeclared identifier 'UHID_DATA_MAX'
  292 |                 max_buffer_size = UHID_DATA_MAX;
      |                                   ^~~~~~~~~~~~~
../drivers/hid/hid-core.c:1777:3: error: use of undeclared identifier 'max_buffer_size'; did you mean 'max_mem_size'?
 1777 |                 max_buffer_size = UHID_DATA_MAX;
      |                 ^~~~~~~~~~~~~~~
      |                 max_mem_size
../include/linux/memory_hotplug.h:116:12: note: 'max_mem_size' declared here
  116 | extern u64 max_mem_size;
      |            ^
../drivers/hid/hid-core.c:1777:21: error: use of undeclared identifier 'UHID_DATA_MAX'
 1777 |                 max_buffer_size = UHID_DATA_MAX;
      |                                   ^~~~~~~~~~~~~
../drivers/hid/hid-core.c:1779:40: error: use of undeclared identifier 'max_buffer_size'; did you mean 'max_mem_size'?
 1779 |         if (report_enum->numbered && rsize >= max_buffer_size)
      |                                               ^~~~~~~~~~~~~~~
      |                                               max_mem_size
../include/linux/memory_hotplug.h:116:12: note: 'max_mem_size' declared here
  116 | extern u64 max_mem_size;
      |            ^
../drivers/hid/hid-core.c:1780:11: error: use of undeclared identifier 'max_buffer_size'; did you mean 'max_mem_size'?
 1780 |                 rsize = max_buffer_size - 1;
      |                         ^~~~~~~~~~~~~~~
      |                         max_mem_size
../include/linux/memory_hotplug.h:116:12: note: 'max_mem_size' declared here
  116 | extern u64 max_mem_size;
      |            ^
../drivers/hid/hid-core.c:1781:19: error: use of undeclared identifier 'max_buffer_size'; did you mean 'max_mem_size'?
 1781 |         else if (rsize > max_buffer_size)
      |                          ^~~~~~~~~~~~~~~
      |                          max_mem_size
../include/linux/memory_hotplug.h:116:12: note: 'max_mem_size' declared here
  116 | extern u64 max_mem_size;
      |            ^
../drivers/hid/hid-core.c:1782:11: error: use of undeclared identifier 'max_buffer_size'; did you mean 'max_mem_size'?
 1782 |                 rsize = max_buffer_size;
      |                         ^~~~~~~~~~~~~~~
      |                         max_mem_size
../include/linux/memory_hotplug.h:116:12: note: 'max_mem_size' declared here
  116 | extern u64 max_mem_size;
      |            ^
8 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>