net: ipv4: Remove an MPTCP variable type guard
Since commit [1], tcp_v4_send_synack is already declared static.

../net/ipv4/tcp_ipv4.c:1067:1: error: duplicate 'static' declaration specifier [-Werror,-Wduplicate-decl-specifier]
 1067 | static int tcp_v4_send_synack(const struct sock *sk, struct dst_entry *dst,
      | ^~~~~~
1 error generated.

[1] 0a01d1a16611fc68c25a171aa868557b3479710d ("BACKPORT: bpf: tcp: Add bpf_skops_hdr_opt_len() and bpf_skops_write_hdr_opt()")

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>