net: bluetooth/hci_sock: Fix broken comment breaking build
Samsung comments out the legacy HCI sock ioctl functionality.

Somehow, that single comment was causing all of this:

../net/bluetooth/hci_sock.c:980:2: error: '/*' within block comment [-Werror,-Wcomment]
  980 |         /* Make sure the cmd is valid before doing anything */
      |         ^
../net/bluetooth/hci_sock.c:1008:12: error: use of undeclared identifier 'sk'
 1008 |         lock_sock(sk);
      |                   ^~
../net/bluetooth/hci_sock.c:1010:13: error: use of undeclared identifier 'sk'
 1010 |         if (hci_pi(sk)->channel != HCI_CHANNEL_RAW) {
      |                    ^~
../net/bluetooth/hci_sock.c:1011:3: error: use of undeclared identifier 'err'
 1011 |                 err = -EBADFD;
      |                 ^~~
../net/bluetooth/hci_sock.c:1021:6: error: implicit declaration of function 'hci_sock_gen_cookie' [-Werror,-Wimplicit-function-declaration]
 1021 |         if (hci_sock_gen_cookie(sk)) {
      |             ^
../net/bluetooth/hci_sock.c:1021:6: note: did you mean 'hci_sock_get_cookie'?
../net/bluetooth/hci_sock.c:93:5: note: 'hci_sock_get_cookie' declared here
   93 | u32 hci_sock_get_cookie(struct sock *sk)
      |     ^
../net/bluetooth/hci_sock.c:1021:26: error: use of undeclared identifier 'sk'
 1021 |         if (hci_sock_gen_cookie(sk)) {
      |                                 ^~
../net/bluetooth/hci_sock.c:1025:22: error: use of undeclared identifier 'sk'
 1025 |                         hci_sock_set_flag(sk, HCI_SOCK_TRUSTED);
      |                                           ^~
../net/bluetooth/hci_sock.c:1028:9: error: implicit declaration of function 'create_monitor_ctrl_open' [-Werror,-Wimplicit-function-declaration]
 1028 |                 skb = create_monitor_ctrl_open(sk);
      |                       ^
../net/bluetooth/hci_sock.c:1028:9: note: did you mean 'create_monitor_ctrl_command'?
../net/bluetooth/hci_sock.c:591:24: note: 'create_monitor_ctrl_command' declared here
  591 | static struct sk_buff *create_monitor_ctrl_command(struct sock *sk, u16 index,
      |                        ^
../net/bluetooth/hci_sock.c:1028:34: error: use of undeclared identifier 'sk'
 1028 |                 skb = create_monitor_ctrl_open(sk);
      |                                                ^~
../net/bluetooth/hci_sock.c:1036:15: error: use of undeclared identifier 'sk'
 1036 |         release_sock(sk);
      |                      ^~
../net/bluetooth/hci_sock.c:1040:27: error: use of undeclared identifier 'argp'; did you mean 'arg'?
 1040 |                 return hci_get_dev_list(argp);
      |                                         ^~~~
      |                                         arg
../net/bluetooth/hci_sock.c:971:20: note: 'arg' declared here
  971 |                           unsigned long arg)
      |                                         ^
../net/bluetooth/hci_sock.c:1040:27: error: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
 1040 |                 return hci_get_dev_list(argp);
      |                                         ^~~~
../include/net/bluetooth/hci_core.h:1090:35: note: passing argument to parameter 'arg' here
 1090 | int hci_get_dev_list(void __user *arg);
      |                                   ^
../net/bluetooth/hci_sock.c:1043:27: error: use of undeclared identifier 'argp'; did you mean 'arg'?
 1043 |                 return hci_get_dev_info(argp);
      |                                         ^~~~
      |                                         arg
../net/bluetooth/hci_sock.c:971:20: note: 'arg' declared here
  971 |                           unsigned long arg)
      |                                         ^
../net/bluetooth/hci_sock.c:1043:27: error: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
 1043 |                 return hci_get_dev_info(argp);
      |                                         ^~~~
../include/net/bluetooth/hci_core.h:1091:35: note: passing argument to parameter 'arg' here
 1091 | int hci_get_dev_info(void __user *arg);
      |                                   ^
../net/bluetooth/hci_sock.c:1046:28: error: use of undeclared identifier 'argp'; did you mean 'arg'?
 1046 |                 return hci_get_conn_list(argp);
      |                                          ^~~~
      |                                          arg
../net/bluetooth/hci_sock.c:971:20: note: 'arg' declared here
  971 |                           unsigned long arg)
      |                                         ^
../net/bluetooth/hci_sock.c:1046:28: error: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
 1046 |                 return hci_get_conn_list(argp);
      |                                          ^~~~
../include/net/bluetooth/hci_core.h:1092:36: note: passing argument to parameter 'arg' here
 1092 | int hci_get_conn_list(void __user *arg);
      |                                    ^
../net/bluetooth/hci_sock.c:1078:27: error: use of undeclared identifier 'argp'; did you mean 'arg'?
 1078 |                 return hci_dev_cmd(cmd, argp);
      |                                         ^~~~
      |                                         arg
../net/bluetooth/hci_sock.c:971:20: note: 'arg' declared here
  971 |                           unsigned long arg)
      |                                         ^
../net/bluetooth/hci_sock.c:1078:27: error: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'void *' [-Wint-conversion]
 1078 |                 return hci_dev_cmd(cmd, argp);
      |                                         ^~~~
../include/net/bluetooth/hci_core.h:1089:48: note: passing argument to parameter 'arg' here
 1089 | int hci_dev_cmd(unsigned int cmd, void __user *arg);
      |                                                ^
../net/bluetooth/hci_sock.c:1081:22: error: use of undeclared identifier 'argp'; did you mean 'arg'?
 1081 |                 return hci_inquiry(argp);
      |                                    ^~~~
      |                                    arg
../net/bluetooth/hci_sock.c:971:20: note: 'arg' declared here
  971 |                           unsigned long arg)
      |                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>