include: dt-bindings: display: add missing display mode flag
Follow up of https://github.com/xfwdrev/android_kernel_samsung_ex2100/commit/8467d9136e88235904c997a21e826f7a62b26401

Fixes error:

In file included from ../drivers/video/fbdev/exynos/panel/s6e3fc3/s6e3fc3.c:17:
In file included from ../drivers/video/fbdev/exynos/panel/s6e3fc3/s6e3fc3_panel.h:3:
In file included from ../drivers/video/fbdev/exynos/panel/s6e3fc3/s6e3fc3_r9_a4_s0_panel.h:31:
../drivers/video/fbdev/exynos/panel/s6e3fc3/s6e3fc3_r9_resol.h:94:11: error: use of undeclared identifier 'PANEL_DISPLAY_MODE_1080x2340_60HS_120HS_TE_HW_SKIP_1'
   94 |                 .name = PANEL_DISPLAY_MODE_1080x2340_60HS_120HS_TE_HW_SKIP_1,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[7]: *** [../scripts/Makefile.build:286: drivers/video/fbdev/exynos/panel/s6e3fc3/s6e3fc3.o] Error 1
make[6]: *** [../scripts/Makefile.build:556: drivers/video/fbdev/exynos/panel/s6e3fc3] Error 2
make[5]: *** [../scripts/Makefile.build:556: drivers/video/fbdev/exynos/panel] Error 2
make[5]: *** Waiting for unfinished jobs....

Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>