video: exynos/panel: ea8082: Fix build with DDI Flash
Another feature that's been half baked by Samsung into this panel driver.

Add stub functions just so it compiles.

Errors:

In file included from ../drivers/video/fbdev/exynos/panel/ea8082/ea8082.c:17:
In file included from ../drivers/video/fbdev/exynos/panel/ea8082/ea8082_panel.h:3:
../drivers/video/fbdev/exynos/panel/ea8082/ea8082_r9_a2_s0_panel.h:1201:27: error: use of undeclared identifier 'do_gamma_flash_checksum'
 1201 |                 .gamma_flash_checksum = do_gamma_flash_checksum,
      |                                         ^
../drivers/video/fbdev/exynos/panel/ea8082/ea8082_r9_a2_s0_panel.h:1202:22: error: use of undeclared identifier 'ea8082_mtp_gamma_check'; did you mean 'panel_mtp_gamma_check'?
 1202 |                 .mtp_gamma_check = ea8082_mtp_gamma_check,
      |                                    ^~~~~~~~~~~~~~~~~~~~~~
      |                                    panel_mtp_gamma_check
../drivers/video/fbdev/exynos/panel/ea8082/../panel_drv.h:496:5: note: 'panel_mtp_gamma_check' declared here
  496 | int panel_mtp_gamma_check(struct panel_device *panel);
      |     ^
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>